USE pokemon_tcg;

INSERT INTO tbl_cards (hp, name, typeId, stageId, info, attack, dammage, weak, ressis, retreat, cardNumberInCollection, collectionSetId)
VALUES
(100, 'Gengar', 5, 3, 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.', 'Shadow Punch', '40', 'Psychic', '', '2', 31, 1),
(80, 'Geodude', 6, 1, 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.', 'Tackle', '10', 'Grass', '', '2', 32, 1),
(100, 'Graveler', 6, 2, 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.', 'Rock Throw', '30', 'Grass', '', '4', 33, 1),
(120, 'Golem', 6, 3, 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'Explosion', '60', 'Grass', '', '3', 34, 1),
(60, 'Slowpoke', 3, 1, 'Incredibly slow and dopey. It takes five seconds for it to feel pain when under attack.', 'Headbutt', '20', 'Electric', '', '2', 35, 1),
(80, 'Slowbro', 3, 2, 'The Shellder that is latched onto Slowpoke’s tail is said to feed on the host’s leftover scraps.', 'Surf', '40', 'Electric', '', '3', 36, 1),
(100, 'Slowking', 3, 3, 'When its head was bitten, toxins entered Slowpoke’s head and unlocked an extraordinary power.', 'Psychic', '60', 'Electric', '', '4', 37, 1),
(70, 'Onix', 6, 1, 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.', 'Rock Throw', '30', 'Grass', '', '3', 38, 1),
(90, 'Machop', 6, 1, 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.', 'Karate Chop', '20', 'Psychic', '', '2', 39, 1),
(110, 'Machoke', 6, 2, 'Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.', 'Submission', '50', 'Psychic', '', '3', 40, 1),
(130, 'Machamp', 6, 3, 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.', 'Dynamic Punch', '70', 'Psychic', '', '4', 41, 1),
(70, 'Gastly', 5, 1, 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.', 'Lick', '20', 'Psychic', '', '1', 42, 1),
(100, 'Haunter', 5, 2, 'Because of its ability to slip through block walls, it is said to be from another dimension.', 'Shadow Ball', '40', 'Psychic', '', '2', 43, 1),
(70, 'Koffing', 5, 1, 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.', 'Smog', '20', 'Psychic', '', '1', 44, 1),
(90, 'Weezing', 5, 2, 'Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years.', 'Sludge', '30', 'Psychic', '', '2', 45, 1),
(60, 'Tangela', 1, 1, 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.', 'Vine Whip', '20', 'Fire', '', '2', 46, 1),
(80, 'Magikarp', 3, 1, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.', 'Splash', '10', 'Electric', '', '1', 47, 1),
(150, 'Gyarados', 3, 2, 'Brutally vicious and enormously destructive. Known for totally destroying cities in ancient times.', 'Dragon Rage', '60', 'Electric', '', '5', 48, 1),
(90, 'Ditto', 11, 1, 'Capable of copying an opponent’s genetic code to instantly transform itself into a duplicate of the enemy.', 'Transform', '0', 'Fighting', '', '1', 49, 1),
(100, 'Snorlax', 11, 1, 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.', 'Body Slam', '50', 'Fighting', '', '4', 50, 1),
(110, 'Articuno', 3, 1, 'A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow.', 'Ice Beam', '70', 'Electric', '', '3', 51, 1),
(110, 'Zapdos', 4, 1, 'A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.', 'Thunder', '80', 'Rock', '', '3', 52, 1),
(110, 'Moltres', 2, 1, 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.', 'Flamethrower', '70', 'Water', '', '3', 53, 1),
(70, 'Dratini', 10, 1, 'Long considered a mythical Pokémon until recently when a small colony was found living underwater.', 'Twister', '20', 'Ice', '', '1', 54, 1),
(90, 'Dragonair', 10, 2, 'A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions.', 'Dragon Breath', '40', 'Ice', '', '2', 55, 1),
(120, 'Dragonite', 10, 3, 'An extremely rare Pokémon that appears only if there is a massive outbreak of wild Pokémon.', 'Hyper Beam', '100', 'Ice', '', '5', 56, 1),
(70, 'Mewtwo', 5, 1, 'It was created by a scientist after years of horrific gene-splicing and DNA-engineering experiments.', 'Psystrike', '80', 'Bug', '', '2', 57, 1),
(50, 'Mew', 5, 1, 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.', 'Psychic', '40', 'Bug', '', '1', 58, 1),
(70, 'Kabuto', 6, 1, 'A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago.', 'Absorb', '10', 'Grass', '', '1', 59, 1),
(90, 'Kabutops', 6, 2, 'It swims gracefully along the sea floor. It also has incredibly sharp sickles that can cut through underwater rocks.', 'Slash', '40', 'Grass', '', '2', 60, 1),
(70, 'Aerodactyl', 6, 1, 'A ferocious, prehistoric Pokémon that goes for the enemy’s throat with its serrated, saw-like fangs.', 'Wing Attack', '30', 'Electric', '', '3', 61, 1);