USE pokemon_tcg;

INSERT INTO tbl_cards (hp, name, typeId, stageId, info, attack, dammage, weak, ressis, retreat, cardNumberInCollection, collectionSetId)
VALUES
(50, 'Sandshrew', 6, 1, 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.', 'Scratch', '10', 'Water', '', '1', 62, 1),
(70, 'Sandslash', 6, 2, 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.', 'Slash', '20', 'Water', '', '2', 63, 1),
(60, 'Nidoran♀', 5, 1, 'Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.', 'Poison Sting', '10', 'Psychic', '', '1', 64, 1),
(70, 'Nidorina', 5, 2, 'When resting deep in its burrow, its thorns always retract. It stays alert for potential foes.', 'Double Kick', '20', 'Psychic', '', '2', 65, 1),
(90, 'Nidoqueen', 5, 3, 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.', 'Earthquake', '30', 'Water', '', '3', 66, 1),
(70, 'Nidoran♂', 5, 1, 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.', 'Horn Attack', '20', 'Psychic', '', '1', 67, 1),
(80, 'Nidorino', 5, 2, 'Quick to anger, it stabs enemies with its horn to inject a powerful poison when it becomes agitated.', 'Horn Drill', '40', 'Psychic', '', '2', 68, 1),
(100, 'Nidoking', 5, 3, 'It swings its big tail around during battle. If its foe flinches, it takes advantage of that moment to quickly finish it off.', 'Megahorn', '60', 'Water', '', '3', 69, 1),
(50, 'Clefairy', 11, 1, 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.', 'Pound', '10', 'Steel', '', '1', 70, 1),
(70, 'Clefable', 11, 2, 'A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people.', 'Double Slap', '30', 'Steel', '', '2', 71, 1),
(40, 'Vulpix', 2, 1, 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.', 'Quick Attack', '10', 'Water', '', '1', 72, 1),
(60, 'Ninetales', 2, 2, 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse.', 'Flamethrower', '30', 'Water', '', '2', 73, 1),
(90, 'Jigglypuff', 5, 1, 'Uses its voice to lull opponents to sleep. The longer it sings, the more deeply its foe falls asleep.', 'Sing', '20', 'Steel', '', '1', 74, 1),
(120, 'Wigglytuff', 5, 2, 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.', 'Hyper Voice', '40', 'Steel', '', '2', 75, 1),
(80, 'Zubat', 5, 1, 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.', 'Wing Attack', '20', 'Electric', '', '1', 76, 1),
(100, 'Golbat', 5, 2, 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.', 'Bite', '30', 'Electric', '', '2', 77, 1),
(60, 'Oddish', 1, 1, 'During the day, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight.', 'Absorb', '10', 'Fire', '', '1', 78, 1),
(70, 'Gloom', 1, 2, 'The fluid that oozes from its mouth isn’t drool. It is a nectar that is used to attract prey.', 'Stun Spore', '20', 'Fire', '', '2', 79, 1),
(90, 'Vileplume', 1, 3, 'Its petals are the largest in the world. As it walks, it scatters extremely allergenic pollen.', 'Petal Dance', '30', 'Fire', '', '3', 80, 1),
(100, 'Paras', 1, 1, 'Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.', 'Scratch', '10', 'Fire', '', '1', 81, 1),
(70, 'Parasect', 1, 2, 'The bug host is drained of energy by the mushrooms on its back. They appear to do all the thinking.', 'Spore', '20', 'Fire', '', '2', 82, 1),
(50, 'Venonat', 5, 1, 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.', 'Confusion', '10', 'Psychic', '', '1', 83, 1),
(80, 'Venomoth', 5, 2, 'The powdery scales on its wings are hard to remove. They also contain poison that leaks out on contact.', 'Psybeam', '30', 'Psychic', '', '2', 84, 1),
(60, 'Diglett', 6, 1, 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.', 'Dig', '10', 'Water', '', '1', 85, 1),
(100, 'Dugtrio', 6, 2, 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.', 'Mud-Slap', '30', 'Water', '', '2', 86, 1),
(40, 'Meowth', 7, 1, 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.', 'Scratch', '10', 'Fighting', '', '1', 87, 1),
(90, 'Persian', 7, 2, 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.', 'Bite', '20', 'Fighting', '', '2', 88, 1),
(60, 'Psyduck', 3, 1, 'While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.', 'Water Gun', '10', 'Electric', '', '1', 89, 1),
(80, 'Golduck', 3, 2, 'Often seen swimming elegantly by lakeshores. It is often mistaken for the Japanese monster Kappa.', 'Hydro Pump', '30', 'Electric', '', '2', 90, 1),
(70, 'Mankey', 6, 1, 'Extremely quick to anger. It could be docile one moment and then thrashing away the next instant.', 'Karate Chop', '10', 'Psychic', '', '1', 91, 1),
(100, 'Primeape', 6, 2, 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.', 'Cross Chop', '30', 'Psychic', '', '2', 92, 1);